"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { Download } from "lucide-react";
import { Navigation } from "@/components/Navigation";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import CallDetailCard from "@/components/ui/call-detail-card";
import { getToken, getCurrentUser, removeToken } from "@/lib/api";
import type { User } from "@/lib/api";

interface CallRecord {
  id: string;
  name: string;
  date: string;
  time: string;
  duration: string;
  mood: string;
  reportUrl?: string;
}

export default function CallHistory() {
  const [selectedCall, setSelectedCall] = useState<CallRecord | null>(null);
  const [user, setUser] = useState<User | null>(null);
  const [loading, setLoading] = useState(true);
  const router = useRouter();

  useEffect(() => {
    const checkAuth = async () => {
      const token = getToken();
      if (!token) {
        router.push("/login");
        return;
      }

      try {
        const userData = await getCurrentUser(token);
        
        // Employees can only access welcome page - redirect them
        if (userData.role === "employee") {
          router.push("/welcome");
          return;
        }

        // Only admins can access this page
        if (userData.role !== "admin") {
          router.push("/login");
          return;
        }

        setUser(userData);
      } catch (error) {
        removeToken();
        router.push("/login");
      } finally {
        setLoading(false);
      }
    };

    checkAuth();
  }, [router]);

  const calls: CallRecord[] = [
    {
      id: "1",
      name: "John Doe",
      date: "28 Dec",
      time: "10:30 PM",
      duration: "12 min",
      mood: "Sad",
      reportUrl: "/reports/john-doe-28-dec.pdf"
    },
    {
      id: "2",
      name: "Jane Smith",
      date: "27 Dec",
      time: "2:15 PM",
      duration: "8 min",
      mood: "Anxious",
      reportUrl: "/reports/jane-smith-27-dec.pdf"
    },
    {
      id: "3",
      name: "Mike Johnson",
      date: "26 Dec",
      time: "9:45 AM",
      duration: "15 min",
      mood: "Calm",
      reportUrl: "/reports/mike-johnson-26-dec.pdf"
    },
    {
      id: "4",
      name: "Sarah Williams",
      date: "25 Dec",
      time: "11:20 PM",
      duration: "10 min",
      mood: "Happy",
      reportUrl: "/reports/sarah-williams-25-dec.pdf"
    },
    {
      id: "5",
      name: "David Brown",
      date: "24 Dec",
      time: "4:30 PM",
      duration: "18 min",
      mood: "Neutral",
      reportUrl: "/reports/david-brown-24-dec.pdf"
    }
  ];

  const generateReport = async (call: CallRecord) => {
    // Generate AI report PDF
    try {
      // TODO: Call backend API to generate PDF report
      // For now, create a simple PDF download
      const reportContent = `
AI-Generated Report for ${call.name}
Date: ${call.date} at ${call.time}
Duration: ${call.duration}
Mood Detected: ${call.mood}

Summary:
This report contains AI-generated insights based on the check-in session.
The analysis includes emotional patterns, key topics discussed, and recommendations.

Generated by Solace AI
      `;

      const blob = new Blob([reportContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${call.name.replace(/\s+/g, '-').toLowerCase()}-report-${call.date.replace(/\s+/g, '-').toLowerCase()}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Error generating report:', error);
      alert('Failed to generate report. Please try again.');
    }
  };

  const getMoodColor = (mood: string) => {
    const colors: Record<string, string> = {
      "Sad": "bg-blue-500",
      "Anxious": "bg-orange-500",
      "Calm": "bg-green-500",
      "Happy": "bg-yellow-500",
      "Neutral": "bg-gray-500"
    };
    return colors[mood] || "bg-gray-500";
  };

  if (loading) {
    return (
      <div className="h-screen bg-black text-white flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-emerald-500 mx-auto"></div>
          <p className="mt-4 text-sm text-gray-400">Loading...</p>
        </div>
      </div>
    );
  }

  if (!user) {
    return null;
  }

  return (
    <div className="min-h-screen bg-black text-white">
      <Navigation />
      
      <div className="px-8 py-8">
        <div className="mb-6">
          <h1 className="text-4xl font-bold mb-2">Reports</h1>
          <p className="text-gray-400">AI-generated reports for employee check-ins.</p>
        </div>

        {/* Minimalistic Table */}
        <div className="overflow-hidden rounded-xl border border-gray-200 bg-white">
          <Table>
            <TableHeader>
              <TableRow className="bg-emerald-500 hover:bg-emerald-500 border-b border-emerald-600/30">
                <TableHead className="h-9 py-2 text-white font-medium border-r border-emerald-600/30">Name</TableHead>
                <TableHead className="h-9 py-2 text-white font-medium border-r border-emerald-600/30">Date</TableHead>
                <TableHead className="h-9 py-2 text-white font-medium border-r border-emerald-600/30">Time</TableHead>
                <TableHead className="h-9 py-2 text-white font-medium border-r border-emerald-600/30">Duration</TableHead>
                <TableHead className="h-9 py-2 text-white font-medium border-r border-emerald-600/30">Mood Detected</TableHead>
                <TableHead className="h-9 py-2 text-white font-medium border-r border-emerald-600/30">Reports</TableHead>
                <TableHead className="h-9 py-2 text-right text-white font-medium">View</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {calls.map((call) => (
                <TableRow key={call.id} className="hover:bg-gray-50/50 border-b border-gray-200/30">
                  <TableCell className="py-3 font-medium text-black border-r border-gray-200/30">{call.name}</TableCell>
                  <TableCell className="py-3 font-medium text-black border-r border-gray-200/30">{call.date}</TableCell>
                  <TableCell className="py-3 text-gray-600 border-r border-gray-200/30">{call.time}</TableCell>
                  <TableCell className="py-3 text-gray-600 border-r border-gray-200/30">{call.duration}</TableCell>
                  <TableCell className="py-3 border-r border-gray-200/30">
                    <span className={`inline-flex items-center px-2.5 py-1 rounded-full text-xs font-medium ${getMoodColor(call.mood)} text-white`}>
                      {call.mood}
                    </span>
                  </TableCell>
                  <TableCell className="py-3 border-r border-gray-200/30">
                    <button
                      onClick={() => generateReport(call)}
                      className="inline-flex items-center gap-2 px-3 py-1.5 bg-emerald-500 hover:bg-emerald-600 text-white text-sm font-medium rounded-lg transition-colors"
                    >
                      <Download size={14} />
                      <span>Download PDF</span>
                    </button>
                  </TableCell>
                  <TableCell className="py-3 text-right">
                    <button
                      onClick={() => setSelectedCall(call)}
                      className="text-blue-600 hover:text-blue-700 transition-colors text-sm font-medium inline-flex items-center gap-1"
                    >
                      <span>▶</span>
                      <span>View</span>
                    </button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      </div>

      {/* Modal for Call Details */}
      {selectedCall && (
        <CallDetailCard call={selectedCall} onClose={() => setSelectedCall(null)} />
      )}
    </div>
  );
}

